Repository zooniverse/caesar, pull requests merged in 2018-10, with the labels that each got.

#456 rerun reducers not extractors!
  app/controllers/workflows_controller.rb
  spec/controllers/workflows_controller_spec.rb
Labels: bug

#474 Include different subjects' extractions in new reductions
  app/models/classification_pipeline.rb
  app/models/extract_fetcher.rb
  app/models/subject.rb
  spec/factories/subject_factory.rb
  spec/models/classification_pipeline_spec.rb
Labels: TESS

#478 some simple attempts to fix the dying exports issue
  app/models/exporters/csv_exporter.rb
  app/operations/creates_data_requests.rb
  app/workers/data_request_worker.rb
Labels: bug, export
