Repository zooniverse/caesar, pull requests merged in 2019-03, with the labels that each got.

#658 Workflow#show fix
  app/views/workflows/show.html.erb
Labels: UI, bug

#624 add id and status columns for rules, add stoplight to rules
  app/models/subject_rule.rb
  app/models/user_rule.rb
  app/views/workflows/_rules.html.erb
Labels: UI, enhancement

#652 order data requests by created date descending
  app/views/workflows/_requests.html.erb
Labels: UI

#661 stop spamming rollbar with "one or more extractors failed"
  app/models/extractor.rb
  app/models/runs_extractors.rb
  config/initializers/rollbar.rb
  spec/models/runs_extractors_spec.rb
Labels: bug, infrastructure

#667 upgrade factory-girl to factory-bot
  Gemfile
  Gemfile.lock
  spec/factories/classification_factory.rb
  spec/factories/credential_factory.rb
  spec/factories/data_request_factory.rb
  spec/factories/extract_factory.rb
  spec/factories/extractor_factory.rb
  spec/factories/project_factory.rb
  spec/factories/reducer_factory.rb
  spec/factories/stream_factory.rb
  spec/factories/subject_action_factory.rb
  spec/factories/subject_factory.rb
  spec/factories/subject_reduction_factory.rb
  spec/factories/subject_rule_effect_factory.rb
  spec/factories/subject_rule_factory.rb
  spec/factories/user_actions.rb
  spec/factories/user_reduction_factory.rb
  spec/factories/user_rule_effect_factory.rb
  spec/factories/user_rule_factory.rb
  spec/factories/workflow_factory.rb
  spec/support/factory_bot.rb
  spec/support/factory_girl.rb
Labels: help wanted, infrastructure, question, security, technical debt

#649 better UI for subjects
  app/controllers/subjects_controller.rb
  app/models/project.rb
  app/models/workflow.rb
  app/views/projects/_subjects.html.erb
  app/views/projects/show.html.erb
  app/views/subjects/show.html.erb
  app/views/workflows/_subjects.html.erb
  config/routes.rb
Labels: UI

#673 don't load the subject pane while it is stil really slowwwww
  app/views/projects/show.html.erb
  app/views/workflows/show.html.erb
Labels: bug

#712 add approved label github action
  .github/main.workflow
Labels: approved

#716 Disable concurrent Jenkins builds and fix staging deployments
  Jenkinsfile
Labels: approved

#731 Ported docs, new docs
  docs/source/includes/_reducer_configuration.md
  docs/source/includes/_reduction_mode.md
  docs/source/includes/_subject_metadata.md
  docs/source/index.html.md
Labels: approved

#733 fix rollbar spam from extractors
  app/models/runs_extractors.rb
  spec/models/runs_extractors_spec.rb
Labels: approved
