Repository zooniverse/caesar, pull requests merged in 2019-01, with the labels that each got.

#573 could not create or edit reducers
  app/views/reducers/_form.html.erb
Labels: UI, bug, configuration

#579 Fix rerunning extractors
  app/controllers/workflows_controller.rb
  app/models/workflow.rb
  spec/controllers/workflows_controller_spec.rb
  spec/factories/reducer_factory.rb
  spec/models/workflow_spec.rb
  spec/support/pundit_helpers.rb
Labels: bug

#575 unbreak rerun_reducers
  app/models/is_reducible.rb
  spec/controllers/subject_reductions_controller_spec.rb
  spec/controllers/user_reductions_controller_spec.rb
  spec/models/project_spec.rb
  spec/models/runs_extractors_spec.rb
  spec/models/workflow_spec.rb
Labels: NFN, bug
