Repository zooniverse/caesar, pull requests merged in 2019-04, with the labels that each got.

#740 Don't save NoData extractions
  app/models/extractors/pluck_field_extractor.rb
  app/models/runs_extractors.rb
  spec/models/extractors/pluck_field_extractor_spec.rb
  spec/models/runs_extractors_spec.rb
Labels: approved

#746 don't try to reduce when there are no extracts to be reduced
  app/models/reducer.rb
  spec/models/reducer_spec.rb
Labels: TESS, aggregation, approved, configuration

#748 Add kubenetes config to caesar staging
  Jenkinsfile
  kubernetes/deployment.tmpl
  kubernetes/redis.yaml
Labels: approved

#751 Add nginx to serve static assets
  docker/start-puma.sh
  kubernetes/deployment.tmpl
  kubernetes/nginx.yaml
Labels: approved

#757 don't allow null values for subgroups
  app/models/extract_grouping.rb
  spec/models/extract_grouping_spec.rb
Labels: approved, bug

#754 Move asset copy to deployment template.
  docker/start-puma.sh
  kubernetes/deployment.tmpl
  kubernetes/nginx.yaml
Labels: approved
