Repository zooniverse/caesar, pull requests merged in 2019-07, with the labels that each got.

#861 Disable transaction to add index concurrently
  db/migrate/20190530163752_add_lock_version_index_to_reductions.rb
Labels: approved

#862 remove merge artifact in text_transform.rb
  app/models/conditions/text_transform.rb
Labels: bug

#865 do not call save if user_id is null on a user reduction
  app/models/runs_reducers.rb
  spec/models/runs_reducers_spec.rb
Labels: approved

#864 consider subject action successful if subject was already in collection
  app/models/effects/add_subject_to_collection.rb
  spec/models/effects/add_subject_to_collection_spec.rb
Labels: approved

#700 find reductions in-place instead of hitting the db
  app/models/reducer.rb
  app/models/reduction_fetcher.rb
  spec/models/reducer_spec.rb
Labels: approved

#866 add chat ops logging for job success and failure
  Jenkinsfile
Labels: approved

#830 remove duplicate nested subjects route declaration
  config/routes.rb
Labels: approved

#879 Fix delete resources
  app/controllers/extractors_controller.rb
  app/controllers/reducers_controller.rb
  app/controllers/subject_rule_effects_controller.rb
  app/controllers/subject_rules_controller.rb
  app/controllers/user_rule_effects_controller.rb
  app/controllers/user_rules_controller.rb
  spec/controllers/extractors_controller_spec.rb
  spec/controllers/reducers_controller_spec.rb
  spec/controllers/subject_rule_effects_controller_spec.rb
  spec/controllers/subject_rules_controller_spec.rb
  spec/controllers/user_rule_effects_controller_spec.rb
  spec/controllers/user_rules_controller_spec.rb
Labels: approved

#880 bail out of export worker if status is set to canceling
  app/models/data_request.rb
  app/workers/data_request_worker.rb
  spec/workers/data_request_worker_spec.rb
Labels: approved

#882 add external effect ui elements
  app/views/subject_rules/_effect.html.erb
  app/views/subject_rules/edit.html.erb
  app/views/user_rules/_effect.html.erb
  app/views/user_rules/edit.html.erb
Labels: approved

#883 counter caches should default to 0
  db/migrate/20190710204342_set_workflow_counter_cache_defaults.rb
  db/schema.rb
Labels: approved

#888 use a different port for the sidekiq docker app
  docker-compose.yml
Labels: approved

#875 use image_tag for static assets
  app/views/application/_header.html.erb
Labels: approved

#892 Add strong migrations gem and initializer
  Gemfile
  Gemfile.lock
  config/initializers/strong_migrations.rb
Labels: approved

#902 Switch staging to env variable secrets
  Gemfile
  Gemfile.lock
  config/initializers/dotenv.rb
  docker/start-app.sh
  docker/start-puma.sh
  docker/start-sidekiq.sh
  kubernetes/deployment-staging.tmpl
Labels: approved

#909 fix k8 staging deploy template
  kubernetes/deployment-staging.tmpl
Labels: approved

#903 Switch production to env secrets
  kubernetes/deployment-production.tmpl
Labels: approved

#893 it never makes sense to reduce by user for nil userid
  app/models/extract_fetcher.rb
  app/models/reducer.rb
  app/models/runs_reducers.rb
  spec/models/extract_fetcher_spec.rb
  spec/models/runs_reducers_spec.rb
Labels: approved

#881 increase kinesis timeout to 60
  kinesis-to-http/caesar_forwarder_production.json
Labels: approved

#885 ignore nonstructured data returned from external extractors and reducers
  lib/http_operation.rb
Labels: approved

#886 add workflow version field to extracts, copy from classification
  app/models/runs_extractors.rb
  db/migrate/20190710214129_add_workflow_version_to_extracts.rb
  db/schema.rb
Labels: approved

#876 fix exports for i2a
  app/controllers/data_requests_controller.rb
  app/models/project.rb
  app/models/workflow.rb
  app/operations/creates_data_requests.rb
  spec/controllers/data_requests_controller_spec.rb
  spec/models/project_spec.rb
  spec/models/workflow_spec.rb
Labels: API, approved, bug, intro2astro

#919 log and stop on any startup errors
  Dockerfile
  docker-compose.yml
  docker/start-app.sh
  docker/start-puma.sh
  docker/start-sidekiq.sh
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
Labels: approved

#920 use explicit REDIS_URL for production sidekiq
  kubernetes/deployment-production.tmpl
Labels: approved

#887 switch the jemalloc for the default ruby memory allocator
  Dockerfile
Labels: approved

#925 do not colocate sidekiq pods on k8 nodes
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
Labels: approved

#926 Add authenticate method for FakeCredential model
  app/models/fake_credential.rb
Labels: approved

#929 Revert "do not colocate sidekiq pods on k8 nodes"
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
Labels: approved

#930 Fix node anti affinity deployment configs
  kubernetes/deployment-production.tmpl
  kubernetes/deployment-staging.tmpl
Labels: approved

#922 mount the local code to the correct dir
  docker-compose.yml
Labels: approved

#938 avoid duplicate CI runs on PR and branch pushes
  .travis.yml
Labels: approved

#932 fix broken lookup of pre-fetched reductions
  app/models/reduction_fetcher.rb
  spec/models/reduction_fetcher_spec.rb
Labels: approved

#939 Remove classification count from dashboard
  app/models/application_status.rb
  app/views/status/show.html.erb
Labels: approved

#934 a rake task to repair busted nfn reductions
  lib/tasks/repair_nfn.rake
Labels: approved

#935 a rake task to rerun tess user reductions that were broken
  lib/tasks/repair_tess.rake
Labels: approved

#936 add another test for grouping
  spec/models/extract_grouping_spec.rb
Labels: approved

#945 make sure that the data connection is set up properly
  lib/tasks/repair_nfn.rake
  lib/tasks/repair_tess.rake
Labels: approved

#947 actually use the actual name of the actual class
  lib/tasks/repair_nfn.rake
Labels: approved
