Repository zooniverse/caesar, pull requests merged in 2019-08, with the labels that each got.

#957 Allow resources to be either paused or halted
  app/controllers/projects_controller.rb
  app/controllers/workflows_controller.rb
  app/models/is_reducible.rb
  app/models/project.rb
  app/models/workflow.rb
  app/views/projects/_settings.html.erb
  app/views/projects/_summary.html.erb
  app/views/projects/index.html.erb
  app/views/workflows/_settings.html.erb
  app/views/workflows/_summary.html.erb
  app/views/workflows/index.html.erb
  app/workers/check_rules_worker.rb
  app/workers/extract_worker.rb
  app/workers/perform_subject_action_worker.rb
  app/workers/perform_user_action_worker.rb
  app/workers/reduce_worker.rb
  spec/workers/check_rules_worker_spec.rb
  spec/workers/extract_worker_spec.rb
  spec/workers/perform_subject_action_worker_spec.rb
  spec/workers/perform_user_action_worker_spec.rb
  spec/workers/reduce_worker_spec.rb
Labels: TESS, approved

#940 Fixes #927 - distinguish between integers and strings in the rules
  app/models/conditions/lookup.rb
  app/views/workflows/_condition.html.erb
  spec/models/conditions/lookup_spec.rb
Labels: approved

#960 set extract fetcher strategy early if all reducers are in running mode
  app/models/runs_reducers.rb
Labels: TESS, approved, performance

#963 mention that all reducers for reducible must be running_reductions
  docs/source/includes/_reduction_mode.md
Labels: approved, documentation

#962 Allow workflow or project to specify custom queue name for sidekiq
  app/models/deferred_queue.rb
  app/models/is_reducible.rb
  app/models/runs_extractors.rb
  app/models/runs_reducers.rb
  app/models/stream_events/classification_event.rb
  app/models/workflow.rb
  db/migrate/20190814050525_add_custom_queue_name_to_projects.rb
  db/migrate/20190814050535_add_custom_queue_name_to_workflows.rb
  db/schema.rb
  spec/models/deferred_queue_spec.rb
  spec/models/runs_extractors_spec.rb
  spec/models/runs_reducers_spec.rb
  spec/models/stream_events/classification_event_spec.rb
Labels: approved

#961 Lazier extracts
  app/models/extract_fetcher.rb
  app/models/fetcher_base.rb
  app/models/reducer.rb
  app/models/reduction_fetcher.rb
  app/models/runs_reducers.rb
  spec/models/extract_fetcher_spec.rb
  spec/models/fetcher_base_spec.rb
  spec/models/reducer_spec.rb
  spec/models/reduction_fetcher_spec.rb
  spec/models/runs_reducers_spec.rb
Labels: NFN, TESS, approved, enhancement, performance

#974 Do not send empty extract lists to ext reducers
  app/models/reducers/external_reducer.rb
  spec/models/reducers/external_reducer_spec.rb
Labels: approved

#975 do not call reduce_into with empty list of extracts
  app/models/reducer.rb
  spec/models/reducer_spec.rb
Labels: TESS, approved
